# Generated by Django 5.0.2 on 2025-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONCERT', 'Concert'), ('FESTIVAL', 'Festival'), ('NIGHTLIFE', 'Nightlife'), ('THEATRE', 'Theatre'), ('SPORTS', 'Sports'), ('ARTS', 'Arts & Culture'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_offline_ready',
            field=models.BooleanField(default=False),
        ),
    ]
