# Generated by Django 5.0.2 on 2025-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category_alter_event_is_offline_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attendee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
