# Generated by Django 5.0.2 on 2025-11-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.UUIDField(blank=True, help_text='Linked Yadi Wallet ID', null=True, unique=True),
        ),
    ]
