# Generated by Django 5.0.2 on 2025-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_user_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Flag for auto-generated guest accounts'),
        ),
    ]
