# Generated by Django 5.0.2 on 2025-12-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_update_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_hash',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
